--- #Remove httpd
- hosts: demo
  user: ansible
  become: yes
  connection: ssh
  vars:
          pname: httpd
  tasks:
          - name: remove httpd
            action: yum name='{{pname}}' state=absent

